spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
    baseline-description: "init"
    baseline-version: 0
    locations: "db/migration"
    out-of-order: true
  jackson:
    date-format: "dd-MM-yyyy"
    serialization:
      write-dates-as-timestamps: false

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN}