spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
    baseline-description: "init"
    baseline-version: 0
    locations: "db/migration"
    out-of-order: true

inventory:
  optimisation:
    id: ${PARAMETERS_ID}
